apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-container
        image: yuripierre/devops-project:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
